### PR TITLE
Polygon implementation

### PR DESCRIPTION
**Pull request by paulvl**
I have implemented the Polygon usage, to verify if a point is contained in it or not used in geofences, also the calculation of the polygon area and perimeter.
Please review the code and accepts this contribution =)

### CODE REVIEW

**Comment by mjaschen** [comment]
Hey Paul,

many thanks for your work! I merged the PR locally and I'm writing some unit tests and adjusting the coding style for PSR-2 now.

When I'm done, a new version 0.3 of phpgeo will be released.

Marcus

**Comment by paulvl** [comment]
I'm glad to contribute with your work, has been very usefull for us. I'll be aware of the new release.
Greetings Marcus.

**Comment by mjaschen** [comment]
Hey @paulvl 

the Polygon implementation is now merged and released.

There was a bug in the getSegments() method: the last segment between the last and the first point was missing. I fixed it and added some unit tests.

The area calculation gives us wrong results currently as the calculations aren't done on the ellipsoid but on an flat surface. The proper area calculation is a quite complex beast (you may check out implementation details [here](http://geographiclib.sourceforge.net)).

Again, many thanks for your help!

Marcus

**Comment by paulvl** [comment]
@mjaschen I was looking the GeographicLib solution for area calculations, seems interesting but as you said, is a quite complex beast. Hope I can implement the correct area calculation soon.
Thanks for merging.

**Pull request merged**
